---
title: Graham Art
timezone: UTC
collections:
  category:
    title: Category
    output: true
  oil_thumbnails:
    title: Oil Thumbnails
    output: false
  posts:
    title: Posts
    output: true
  print_thumbnails:
    title: Print Thumbnails
    output: false
  uploads:
    title: Uploads
    output: true
  watercolour_thumbnails:
    title: Watercolour Thumbnails
    output: false
name: Graham Art Gallery
description: Online gallery of an English artist.
author: Graham
author_email: graham.art.uk@gmail.com
category_dir: "/"
url: https://www.grahamart.com
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
image: https://res.cloudinary.com/dtn9ari2r/image/upload/c_thumb,w_200,g_face/v1533736857/oils/hands.jpg
